spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/city
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      sensitive: false
      enabled: true
